version: "3.8"
services:
  eopdsde:
    build: ./docker
    shm_size: "4gb"
    hostname: eopfsde
    privileged: true
    ports:
      - 80:80
      - 9000:9000
    environment:
      - USERNAME=sebastien
      - USERFULLNAME="Sebastien Dorgan"
      - USEREMAIL=sebastien.dorgan@csgroup.eu
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

