name: eopf
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - pip
  - rioxarray
  - dask
  - netcdf4
  - zarr
  - fs
  - h5netcdf
  - pyyaml
  - autopep8
  - geojson
  - pylint
  - mypy
  - cudf
  - distributed
  - dask-cuda
  - cudatoolkit
  - black
  - flake8
  - more-itertools
  - pytest
  - sphinx
  - docker-compose
  - pip:
    - dataclasses-json
    - dataclasses-jsonschema
    - fs-s3fs
    - pyserde
    - ray
    - requests
    - xmltodict
